### ISSUE TITLE
Pushear el código (o eliminar este repo)

### ISSUE THREAD

**Issue by santiagopoli** [argob/cuidar-android#10]
Ya pasaron 30 días desde que crearon este repositorio y aún no pushearon el código. Estaría bueno que lo hagan, ya que es de público interés. Siendo una aplicación en la cual el ciudadano introduce información personal (de forma obligatoria), es indispensable que el código fuente pueda auditarse.

Si no van a compartir el código, al menos borren este repositorio así al menos todos sabemos que no tienen el compromiso necesario para hacer esto.

**Comment by Sophivorus** [comment]
A los desarrolladores de Cuidar: parece que hay un gran interés por su trabajo, ¡felicitaciones! Estoy seguro que si suben el código, colegas y ciudadanos eventualmente enviarán pull requests útiles. ¡Es una gran oportunidad para la app y para empezar a generar una comunidad de desarrollo!

**Comment by otharwa** [comment]
Adhiero al pedido y al interés. Me parece que se puede aprovechar ampliamente la comunidad de desarrolladoras/es de argentina para mejorar las aplicaciones del gobierno argentino.

Es importante que los mecanismos informáticos estatales aplicados a la población, puedan ser auditados por la población (al menos por el sector que posea los conocimientos necesarios para su entendimiento)

**Comment by rusosnith** [comment]
Vengo a festejar el 2 cumplemes de esta promesa incumplida.
