### ISSUE TITLE
Cumplan con lo que prometieron

### ISSUE THREAD

**Issue by brunocar** [argob/cuidar-android#11]
Pusheen el codigo o los reportamos con github.

**Comment by matiasperrone** [comment]
Es igual a #10

**Comment by miparnisari** [comment]
> Pusheen el codigo o los reportamos con github.

No encontre forma de reportar un repo, como se hace? Ticket a soporte? @brunocar

**Comment by brunocar** [comment]
hay que mandarle un email a los de soporte

**Comment by byeze** [comment]
> > Pusheen el codigo o los reportamos con github.
> 
> No encontre forma de reportar un repo, como se hace? Ticket a soporte? @brunocar

Vía: https://support.github.com/contact

**Comment by paulofer85** [comment]
hay que llenar el formulario no? pero mas allá de eso alguien tiene un mail para agilizar la cuestion?
