### ISSUE TITLE
Uso de librerias en versiones alpha

### ISSUE THREAD

**Issue by sebacipolat** [argob/cuidar-android#16]
Estan utilizando librerias en version alpha, no es buena idea

https://github.com/argob/cuidar-android/blob/master/app/build.gradle

**Comment by gastsail** [comment]
Si funciona no habría problemas, el problema está en no aprobar PR que actualicen estas versiones sin ver de antemano los cambios de estas, ya que en cada cambio de version se pueden deprecar componentes o cambiar el naming de muchos componentes

**Comment by martinszy** [comment]
Una de las librerías en cuestión es una librería de criptografía, no revisé bien para qué se está usando, pero coincido con seba en que me sentiría más tranquilo si fuera una versión estable.

**Comment by cuidarapp** [comment]
En 4631dc1 se incorporaron sugerencias de este ticket y los cambios ya fueron mergeados en el repo oficial. Gracias por el aporte!
