### ISSUE TITLE
Unable to resolve host "base.url": No address associated with hostname

### ISSUE THREAD

**Issue by gastsail** [argob/cuidar-android#22]
Parece que la información del BASE_URL dentro de `many - TextUtils` no es la correcta, se podría saber la información correcta de la API para poder hacer las consultas ? 

Se necesita esto para poder pasar la primera pantalla de login

**Comment by cuidarapp** [comment]
Para proteger los datos de la ciudadanía no está autorizado el acceso a la API, está explicado en la README.
Un saludo.
