### ISSUE TITLE
Token de New Relic expuesto

### ISSUE THREAD

**Issue by guadalazzo** [argob/cuidar-android#24]
Hola!
En el file _**app/newrelic.properties**_ tienen expuesto el token para linkear la app con new relic
le recomiento ponerlo en una variable de ambiente por su seguridad.
Saludos.

**Comment by cuidarapp** [comment]
No es el token real, pero gracias por la observación.

**Comment by cuidarapp** [comment]
En el branch `pre-3.5.4-11-08-2020` se dejó más claro que el token es un placeholder y ese cambio ya fue mergeado en el repo oficial. Gracias por el aporte!
