### ISSUE TITLE
¿ Se revisa este repo ?

### ISSUE THREAD

**Issue by gastsail** [argob/cuidar-android#30]
Parece que esta muy abandonado desde que se subio el código, la comunidad quiere contribuir pero parece que hay 0 feedback por parte de CUIDAR con este repo.

**Comment by cuidarapp** [comment]
Acabamos de subir una actualización que refleja todos los PRs e issues que contribuyó la comunidad y que incorporamos al código. Leemos todos los comentarios y tickets y aunque no siempre podemos responder en el momento valoramos mucho el feedback de la comunidad.

**Comment by gastsail** [comment]
Creo que no subieron nada de lo que aportó la comunidad, solo copiaron y pegaron el código de los PR's, no entiendo la seriedad del proyecto @cuidarapp
