### ISSUE TITLE
Pregunta hacia los PR

### ISSUE THREAD

**Issue by gastsail** [argob/cuidar-android#31]
Creo que el objetivo de contribuir a un repo opensource es que los PR que hacemos los mergeen y no los copien y peguen en una version, para eso contribuimos con PR's, el ultimo que hice https://github.com/argob/cuidar-android/pull/27 que se tardo casi 2 semanas en aprobar lo rechazaron, crearon una rama nueva y pegaron lo que hice, osea que no mergearon ni siquiera al nuevo branch lo que mande al PR, me parece que si la idea es que sea un repo open source para contribuir es aprobar los PR que hacemos para contribuir al repo en general, sino van a aparecer todos como rechazados y copiados y pegados, no entiendo

La idea es ayudar a que el código sea mejor, arreglar cosas y aportar, creo que esto le quita todo el sentido a hacerlo y realmente te bajonea, ademas seguimos sin contar con una API dummy para hacer las consultas de prueba al menos, por lo cual no se puede pasar de la pantalla de login, no creo que se tenga que mockear la api desde el cliente , creo que deberian meterle mas pilas si el repo es open source, al menos 1 vez a la semana revisar PR's , chequear el código, aportar buen feedback y mergear los aportes de la gente, no copiar y pegarlos a otra rama, le quita totalmente el sentido a la contribución

**Comment by joaquini** [comment]
Es el peor manejo que he visto de un repo Open Source.
Lamentable realmente.

En cualquier repositorio decente hasta el equipo de desarrollo oficial envía PRs.

**Comment by gastsail** [comment]
> Es el peor manejo que he visto de un repo Open Source.
> Lamentable realmente.
> 
> En cualquier repositorio decente hasta el equipo de desarrollo oficial envía PRs.

Totalmente, parece un repo hecho _**de onda**_  que es un copy/paste del código original que no se mantiene acá, creo que lo subieron para calmar un poco las aguas pero parece que no se le da seguimiento , y como decis, parece que tampoco se trabaja oficialmente en este repo, por lo que es muy poco serio

**Comment by cuidarapp** [comment]
Estimados, el trabajo diario se realiza en los repos internos que están integrados a los ambientes de desarrollo. Cuando se van cumpliendo hitos se suben actualizaciones a github. Las sugerencias de la comunidad que se toman se documentan sucintamente en el `CHANGELOG.md` y como dice ahí mismo, en detalle en el `CONTRIBUTORS.md`, con referencia a cada PR de forma individual, por lo tanto queda registro preciso de qué se toma, y se atribuye apropiadamente el crédito.

Dado que se trabaja de corrido, sin fines de semana, para poder resolver todas las demandas tecnológicas que la pandemia requiere, consideramos que es un equilibrio más que razonable.

**Comment by gastsail** [comment]
En la parte contributors no veo mi contribucion al repo, si se rechazan los PR , se copia y pega al código y se anota en el .md , no forma parte como una contribución, fuera de eso, está todo bien, no hay razón para debatir sobre esto, es solo una sugerencia para manejar mejor las contribuciones

**Comment by cuidarapp** [comment]
Nos faltó incluir algo más además de?

```
Instrucciones para compilar con Firebase y renombre `TextUtils` -> `APIConstants`, @gastsail, https://github.com/argob/cuidar-android/pull/27
```

Si es así te pedimos disculpas. Comentanos por favor qué nos faltó y lo agregamos.

**Comment by gastsail** [comment]
No, eso esta perfecto, lo que pasa es que en el repo en si, en la seccion contributors que son las personas que colaboran co nel proyecto no aparece que yo haya contribuido, por eso detallaba que si para mergear lo que hice y contar como contribucion era necesario rechazar el pull y abrirlo en otra rama, hubiera sido esa la mejor opcion

**Comment by niqueco** [comment]
Sólo quería decir que me parece genial que esté el código, y que tomen en cuenta las contribuciones y los felicito porque no es usual. Lo demás son detalles. Claro que uno puede tener una preferencia casi estética porque se use el mismo repositorio adentro y afuera y se usen los commits originales de uno, pero no es sencillo siempre mezclar el mundo del desarrollo abierto con el mundo del desarrollo dentro de empresas. Nada, perdón por el spam. Saludos! =)

**Comment by gastsail** [comment]
Totalmente @niqueco  , concuerdo con vos 👍  , estaria bueno que este sea el punto oficial de partida tanto para desarrollo como para testing, y estaria bueno que nos aportaran alguna api dummy para poder testear , agregar un CI para automatizar los checks para mergear y asi hacerlo mucho mas mantenible y escalable, me hace un poco de ruido que se tengan ambientes desentendidos de este repo, creo que añade mas responsabilidad al equipo y mas trabajo , en mi opinion

**Comment by joaquini** [comment]
Entiendo el balance, pero es una forma muy curiosa de usar git.
Creo que todas las empresas se enfrentan a desafíos similares y acá realmente está mal llevado a cabo.
El merge que se hace desde los repos internos sencillamente destruye hasta el historial de cambios introducidos en un PR: Pueden ver un [ejemplo acá](https://github.com/argob/cuidar-android/pull/15/files).

Por otro lado, felicito y reconozco el esfuerzo del equipo de desarrollo y ojalá todos los proyectos fueran open source como este.

**Comment by gastsail** [comment]
Exacto @joaquini , no hay trazabilidad con los PR de la forma que se lleva a cabo ahora, la idea sería poder unificar esto con las diferentes ramas o aclarar en el readme sobre en que ramas trabajar para contribuir, ya que muchos PR van a ser directamente a produccion

**Comment by cuidarapp** [comment]
@gastsail se entiende a qué te referís, vamos a buscar la forma de que se refleje también. No podemos mergear los PRs directo, pero alguna vuelta le vamos a buscar. @joaquini luego del PR que comentás que quedó anulado por un push cambiamos la forma de subir los nuevos hitos y lo hacemos con una nueva [rama que mergeamos](https://github.com/argob/cuidar-android/compare/pre-3.5.2...pre-3.5.4-11-08-2020) y dejamos una referencia en cada PR (como [aquí](https://github.com/argob/cuidar-android/pull/27#issuecomment-672828476)).
Nuevamente, creemos que es un buen balance que permite ir dando visibilidad del avance de la aplicación, incorporando las sugerencias y optimizar los tiempos que son escasos. 

Cerramos el ticket, cualquier cosa la seguimos en otro. Un saludo.

**Comment by peorth80** [comment]
+1, podrian por favor dar mas informacion de porque eligieron esta metodologia tan incomoda y poco clara? La idea de publicar la informacion en repositorios de Open Source es justamente, que sea abierto y este disponible. Lo que estan haciendo es ocultar la informacion.
